# Generated by Django 4.0.2 on 2022-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_order_orderrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
