# Generated by Django 4.0.2 on 2022-03-03 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_passport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'started'), ('PAYMENT_SUCCESSFULL', 'payment successfull'), ('PAYMENT_FAILS', 'payment fails'), ('DOING', 'doing'), ('COMPLETED', 'compoleted')], default='INITIATED', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
